apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: seasonal-wardrobe
data:
  NODE_ENV: "production"
  PORT: "5000"
  MONGODB_URI: "mongodb://mongodb-service:27017/seasonal-wardrobe"
