apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: seasonal-wardrobe
type: Opaque
stringData:
  WEATHER_API_KEY: "your_api_key_here"
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "adminpassword"
